name: pawguard_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & platform
  google_maps_flutter: ^2.6.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # Camera & ML
  camera: ^0.11.0
  tflite_flutter: ^0.12.1
  google_mlkit_face_detection: ^0.11.0

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.5

  # Utils
  image: ^4.1.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ssd_mobilenet_v2.tflite
    - assets/labels.txt
    - .env
